"""
Paper Analysis Agent.

Reads one research paper and extracts structured information.
"""

import os

from openai import OpenAI
from dotenv import load_dotenv

import prompts
import json


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
MODEL = "openai/gpt-oss-20b"

if not OPENROUTER_API_KEY:
    raise RuntimeError(
        "OPENROUTER_API_KEY is not set. "
        "Add it to your .env file."
    )


client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY,
)


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

def analyze(paper_text, paper_id):
    """
    Analyze one research paper.

    Args:
        paper_text:
            Complete text of the paper.

        paper_id:
            Identifier of the paper.

    Returns:
        str:
            Structured analysis generated by the LLM.
    """

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "system",
                "content": prompts.PAPER_ANALYSIS_SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": prompts.build_paper_analysis_prompt(
                    paper_text,
                    paper_id,
                ),
            },
        ],
    )

    content = response.choices[0].message.content

    try:
        analysis = json.loads(content)
    except json.JSONDecodeError:
        raise ValueError(
            f"Paper Analysis agent returned invalid JSON:\n{content}"
        )

    return analysis